// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/liquid-glass/DesignSystem.tsx": () => import("../components/mockups/liquid-glass/DesignSystem.tsx"),
  "./components/mockups/liquid-glass/DetailScreen.tsx": () => import("../components/mockups/liquid-glass/DetailScreen.tsx"),
  "./components/mockups/liquid-glass/ExploreScreen.tsx": () => import("../components/mockups/liquid-glass/ExploreScreen.tsx"),
  "./components/mockups/liquid-glass/HomeScreen.tsx": () => import("../components/mockups/liquid-glass/HomeScreen.tsx")
};
